### ISSUE TITLE
timing out every time

### ISSUE THREAD

**Issue by odds-get-evened** [nadeemabdulhamid/PeerBase#1]
i cloned this repo, and tried using the python peer, but no matter what I do it still times out every time. help please! i would really like to extend from this codebase, but even with all firewalls turned off, the main service never gets established on local machine.

**Comment by nadeemabdulhamid** [comment]
Note that this code was written a long time ago for Python version 2.x, so if you are using Python 3.x, there are probably a number of things that need to be updated in the code in order to get it working again with that.

Otherwise, here is how to run it: Suppose you have two machines with IP addresses, 10.16.100.125  and 10.16.100.210; then in a terminal, 'cd' to the directory where the p2p files (assuming Python version) are stored, and type:

on the 10.16.100.125 machine:
```
    python filergui.py 5277 10  10.16.100.210:5277
```

and on the 10.16.100.210 machine:
```
    python filergui.py 5277 10  10.16.100.125:5277
```

If you are trying to run multiple clients on the same machine, use different ports and 'localhost' as the ip address, e.g.

```
python filergui.py 5277 10 localhost:5278 
python filergui.py 5278 10 localhost:5277 
```

See the attached screenshot for what you should do/see. Once the GUI interface pops up, you can 'add' local files to each peer's list, and 'search' the entire network for files at any peer.

![unnamed](https://user-images.githubusercontent.com/222592/171754215-3a343bcb-2810-46a3-a5a1-e2603a31bb73.png)
